# Artificial Neural Network **Combined Cycle Power Plant**

## Part 1 - Data Preprocessing

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.12.0'

### Importing the dataset

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X[0,:])
print(y[0])

[  14.96   41.76 1024.07   73.17]
463.26


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train)
np.size(X_train)

In [12]:
np.size(X_test)


7656

In [13]:
np.size(X_train)

7654

In [14]:
np.size(y_test)

1914

In [15]:
np.size(y_train)

7654

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
#print(ann.output_shape)
print(ann.compute_output_signature)

<bound method Layer.compute_output_signature of <keras.engine.sequential.Sequential object at 0x7d664df64490>>


### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
print(ann.compute_output_signature)

<bound method Layer.compute_output_signature of <keras.engine.sequential.Sequential object at 0x7d664df64490>>


### Adding the output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [22]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [24]:
ann.fit(X_train,y_train,batch_size=32, epochs=150)

Epoch 1/150
240/240 [==============================] - 1s 2ms/step - loss: 28.1627
Epoch 2/150
240/240 [==============================] - 1s 2ms/step - loss: 27.2844
Epoch 3/150
240/240 [==============================] - 1s 2ms/step - loss: 28.0367
Epoch 4/150
240/240 [==============================] - 1s 2ms/step - loss: 27.3216
Epoch 5/150
240/240 [==============================] - 1s 2ms/step - loss: 27.7349
Epoch 6/150
240/240 [==============================] - 1s 2ms/step - loss: 26.6912
Epoch 7/150
240/240 [==============================] - 1s 2ms/step - loss: 27.7966
Epoch 8/150
240/240 [==============================] - 1s 2ms/step - loss: 27.6396
Epoch 9/150
240/240 [==============================] - 0s 2ms/step - loss: 27.6791
Epoch 10/150
240/240 [==============================] - 1s 2ms/step - loss: 28.2903
Epoch 11/150
240/240 [==============================] - 0s 2ms/step - loss: 27.3272
Epoch 12/150
240/240 [==============================] - 1s 2ms/step - loss: 27.2361
E

### Predicting the results of the Test set

In [26]:
y_pred= ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[431.45 431.23]
 [462.44 460.01]
 [465.93 461.14]
 ...
 [473.2  473.26]
 [439.97 438.  ]
 [459.23 463.28]]


In [36]:
print(np.concatenate((y_pred.reshape(1,len(y_pred)), y_test.reshape(1, len(y_test))),0))

[[431.45 462.44 465.93 ... 473.2  439.97 459.23]
 [431.23 460.01 461.14 ... 473.26 438.   463.28]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')